spring:
  application:
    name: nudge

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9025/realms/api.knox.gb.net/protocol/openid-connect/certs"
